<?php
$sql = <<<EOT
CREATE TABLE `medicine` (
	`auid` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`puid` CHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`suid` CHAR(40) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`tuid` CHAR(70) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`luid` VARCHAR(70) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`entry` VARCHAR(80) NULL DEFAULT 'ORIGIN' COLLATE 'utf8mb4_unicode_ci',
	`author` VARCHAR(90) NULL DEFAULT 'ORIGIN' COLLATE 'utf8mb4_unicode_ci',
	`created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`updated` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`oauthid` CHAR(70) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`generic` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`title` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`description` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`cost` DECIMAL(13,2) NULL DEFAULT NULL,
	`price` DECIMAL(13,2) NULL DEFAULT NULL,
	`quantity` BIGINT(19) NULL DEFAULT NULL,
	`vendor` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`effect` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`type` ENUM('CREAM','INJECTION','TABLET','CAPSULE','SYRUP') NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`storage` ENUM('DISPENSARY','SHELF','FRIDGE','ROOM_TEMPERATURE') NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`status` ENUM('PENDING','INACTIVE','ACTIVE','DELIST') NULL DEFAULT 'PENDING' COLLATE 'utf8mb4_unicode_ci',
	PRIMARY KEY (`auid`) USING BTREE,
	UNIQUE INDEX `puid` (`puid`) USING BTREE,
	UNIQUE INDEX `suid` (`suid`) USING BTREE,
	UNIQUE INDEX `tuid` (`tuid`) USING BTREE,
	INDEX `luid` (`luid`) USING BTREE,
	INDEX `created` (`created`) USING BTREE,
	INDEX `updated` (`updated`) USING BTREE,
	INDEX `entry` (`entry`) USING BTREE,
	INDEX `author` (`author`) USING BTREE,
	INDEX `oauthid` (`oauthid`) USING BTREE,
	INDEX `storage` (`storage`) USING BTREE,
	INDEX `type` (`type`) USING BTREE,
	INDEX `effect` (`effect`) USING BTREE,
	INDEX `quantity` (`quantity`) USING BTREE,
	INDEX `price` (`price`) USING BTREE,
	INDEX `cost` (`cost`) USING BTREE,
	INDEX `title` (`title`) USING BTREE,
	INDEX `vendor` (`vendor`) USING BTREE,
	INDEX `generic` (`generic`) USING BTREE,
	INDEX `status` (`status`) USING BTREE) COLLATE='utf8mb4_unicode_ci' ENGINE=InnoDB ROW_FORMAT=DYNAMIC AUTO_INCREMENT=1;
EOT;
return $sql;